### ISSUE TITLE
PathRemovePrefix bug?

### ISSUE THREAD

**Issue by tnachy** [fzankl/yarp-sample#1]
hi, according to https://microsoft.github.io/reverse-proxy/articles/transforms.html, based on the example given, the PathRemovePrefix will removed the provided prefix and keeps the remaining?

But when I try to add something like ...api/service1/xyz, it seems like the prefix is not removed? Is it Microsoft's bug?
![image](https://user-images.githubusercontent.com/71638307/183840799-eecbcd4a-d2a9-4485-940a-60e4cce3434e.png)

**Comment by fzankl** [comment]
Hi @tnachy,
I've just checked the behavior you discovered during testing and indeed there was an issue.
It's important that the prefix does not end with an '/', otherwise it will not work.

The sample implementation is now modified to consider this behavior (please see PR #2 )
![image](https://user-images.githubusercontent.com/44210522/183979514-57b903ea-da4f-433b-bea9-e09639a57bbf.png)
